[package]
name = "axel"
version = "0.1.0"
authors = ["sdtv9507 <apr8950@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
